
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxfzuexhsgyeruqrmdow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Znp1ZXhoc2d5ZXJ1cXJtZG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyODA3ODMsImV4cCI6MjA1ODg1Njc4M30.6UgFVo4bqZ7UKhNVOc8124GURtNMQRgpLLYV0lE1njg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'skorup-auth-key',
      flowType: 'pkce', // Add explicit PKCE flow for better security
    }
  }
);
